### PR TITLE
Fix/remove skipped test cases

### LINKED ISSUE #470: Remove Skipped Tests and Ensure Test Suite is Running Fully
### Issue Description

Remove all instances of skipped tests in the codebase (tests marked with .skip or similar), and ensure that all tests are running as part of the test suite. This task also includes identifying any issues or failures with previously skipped tests and fixing them if necessary.

**Locate Skipped Tests:**

Search for any tests in the codebase that are marked as skipped (e.g., it.skip, test.skip, describe.skip, etc.).
Remove Skip Flags:

Remove .skip or equivalent flags from all test cases.

**Run the Test Suite:**

Execute the entire test suite using the appropriate test command (e.g., npm test, pnpm test, yarn test).

**Address Failing Tests:**

Investigate and fix any test failures that occur after re-enabling the skipped tests.
Verify Successful Test Run:

Ensure that all tests pass and the suite completes without any skips.
Update Documentation (if needed):

Ensure that test-related documentation reflects any updates or changes, including the resolution of previously skipped tests.### Screenshots

[If applicable, add screenshots or images that help illustrate the issue. You can use the following Markdown syntax to embed images:]

### Environment

- Operating System: [e.g., Windows, macOS, Linux]
- Browser (if applicable): [e.g., Chrome, Firefox, Safari]
- Version of Software/Project: [e.g., v1.0.0]

### Additional Information

[Include any additional context, logs, or details that might be helpful in addressing the issue.]

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

📚 See [contributing instructions](https://github.com/samyakshah3008/mobile-app/blob/develop/CONTRIBUTING.md).

### PR DESCRIPTION
**Pull request by abhisheksharmayt**
Date: 23-10-2024
Developer Name: Abhishek Sharma

---

## Issue Ticket Number
- Closes #470 

## Description
1. Removed .skip from test cases in util-test.ts test cases.
2. Updated test cases and their description wherever required as the function implementation was changed but test cases were not updated(Attached Screenshot).
3. Made sure that all test cases in util-test.ts pass.

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

Screenshot 2024-10-19 002356

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

image

</details>

## Additional Notes

There were a lot of test cases that were skipped, so divided it into multiple PR.
PR(1/5).

### CODE REVIEW

File: __tests__/Util-test.ts [hunk 1]
```diff
@@ -29,12 +30,16 @@ describe('getUserData util', () => {
     username: 'anish-pawaskar',
   };
```
Comment (pankajjs) [inline __tests__/Util-test.ts:31]: Can you move this to fixture?

File: __tests__/Util-test.ts [hunk 2]
```diff
@@ -29,12 +30,16 @@ describe('getUserData util', () => {
...
 
-  test.skip('when url passed !== redirect url return null', async () => {
-    const res = await getUserData('https://www.example.net/');
-    expect(res).toEqual(null);
+  test('when token passed is invalid, axios call returns with 401', async () => {
+    mockedAxios.get.mockRejectedValue('401: Unauthorized');
+    try {
+      await getUserData(invalidToken);
```
Comment (prakashchoudhary07) [inline __tests__/Util-test.ts:44]: Is the function accepting token or userId?

Comment (abhisheksharmayt) [reply __tests__/Util-test.ts:44]: token
image

**Review by iamitprakash — APPROVED** [review]
