### PR TITLE
Fix broken tests for todo component

### LINKED ISSUE #464: Tests are broken
### Issue Description
Tests are failing on executing test command.

### Expected Behavior
Every test should pass.

### Current Behavior
Tests are failing while executing test command.

### Screenshots
Screenshot 2024-10-09 at 10 02 54 PM

### Environment

- Operating System: [e.g., Windows, macOS, Linux]
- Browser (if applicable): [e.g., Chrome, Firefox, Safari]
- Version of Software/Project: [e.g., v1.0.0]

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

📚 See [contributing instructions](https://github.com/samyakshah3008/mobile-app/blob/develop/CONTRIBUTING.md).

### PR DESCRIPTION
**Pull request by pankajjs**
Date: 10 Oct, 2024

Developer Name: Pankaj Sha 

---

## Issue Ticket Number

- closes #464 
## Description

This PR fixes tests.
### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

Screenshot 2024-10-13 at 8 32 53 PM

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

Screenshot 2024-10-13 at 8 34 22 PM

</details>
<details>
<summary>Screenshot 2</summary>

</details>

Screenshot 2024-10-13 at 8 34 47 PM

### CODE REVIEW

**Comment by shreya-mishra** [comment]
@pankajjs can you please add the test coverage report ?

**Comment by pankajjs** [comment]
> @pankajjs can you please add the test coverage report ?

Added.

**Comment by shreya-mishra** [comment]
> > @pankajjs can you please add the test coverage report ?
> 
> Added.

this is not a test coverage, can you run command yarn test --coverage?

File: __tests__/Goals/components/TodoComponent-text.tsx [hunk 1]
```diff
@@ -25,14 +25,19 @@ describe('TodoComponent', () => {
   });
 
   test.skip('calls navigationProp.navigate when "Add" button is pressed', async () => {
```
Comment (shreya-mishra) [inline __tests__/Goals/components/TodoComponent-text.tsx]: why this test is skipped ?

Comment (pankajjs) [reply __tests__/Goals/components/TodoComponent-text.tsx]: Hi @shreya-mishra If you look at it, this test was already there. I just have refactored it because it was causing warning.

Comment (shreya-mishra) [reply __tests__/Goals/components/TodoComponent-text.tsx]: if we remove the skip then test will be failing right ?

Comment (pankajjs) [reply __tests__/Goals/components/TodoComponent-text.tsx]: > hen test will be failing right ?

@shreya-mishra No, It is not.

Comment (shreya-mishra) [reply __tests__/Goals/components/TodoComponent-text.tsx]: then can you please remove skip and then add the test coverage again ?

Comment (pankajjs) [reply __tests__/Goals/components/TodoComponent-text.tsx]: @shreya-mishra There are more skip tests. Should I remove all instance?

Comment (shreya-mishra) [reply __tests__/Goals/components/TodoComponent-text.tsx]: remove it atleast for this file and please check if tests are passing

Comment (pankajjs) [reply __tests__/Goals/components/TodoComponent-text.tsx]: @shreya-mishra Removed skip test and added updated screenshots.

File: __tests__/Goals/components/TodoComponent-text.tsx [hunk 2]
```diff
@@ -23,16 +23,4 @@ describe('TodoComponent', () => {
...
-  test.skip('calls navigationProp.navigate when "Add" button is pressed', async () => {
-    const navigationProp = { navigate: jest.fn() };
-    const { getByTestId } = render(
-      <NavigationContainer>
-        <TodoComponent navigation={navigationProp} />
-      </NavigationContainer>,
-    );
-    const addButton = await getByTestId('addButton');
-    fireEvent.press(addButton);
-    expect(navigationProp.navigate).toHaveBeenCalledWith('CreatingGoals');
```
Comment (shreya-mishra) [inline __tests__/Goals/components/TodoComponent-text.tsx]: I asked you to remove skip from the test :/

Comment (pankajjs) [reply __tests__/Goals/components/TodoComponent-text.tsx]: @shreya-mishra fixed it and added updated test coverage.

**Comment by shreya-mishra** [comment]
Test coverage of toDoComponent is really low, but I think this ticket is about fixing the broken test case then its fine. but we need to cover increase the test coverage.

**Comment by shreya-mishra** [comment]
> Test coverage of toDoComponent is really low, but I think this ticket is about fixing the broken test case then its fine. but we need to cover increase the test coverage.

@pankajjs, please ask for others' opinions too, and ask for review and feedback.

**Comment by pankajjs** [comment]
> Test coverage of toDoComponent is really low, but I think this ticket is about fixing the broken test case then its fine. but we need to cover increase the test coverage.

The scope of issue was limited. 
However, we should increase the test coverage in other issue.

**Review by iamitprakash — CHANGES_REQUESTED** [review]
please keep better PR name

**Review by shreya-mishra — APPROVED** [review]

**Comment by pankajjs** [comment]
> please keep better PR name

Fixed.

**Comment by vinit717** [comment]
Fix the pr name with a better tile to justify your changes as you change only one file 
so you can say like fix broken tests for  todo component text

**Comment by pankajjs** [comment]
> Fix the pr name with a better tile to justify your changes as you change only one file so you can say like fix broken tests for todo component text

@vinit717 fixed it.

**Review by yesyash — APPROVED** [review]

**Review by vinit717 — APPROVED** [review]

**Review by shreya-mishra — APPROVED** [review]
