### PR TITLE
Card UI fix as per the response of the API.

### LINKED ISSUE #184: Card UI fix as per the goals GET response
Card UI fix as per the GET response. This will include card design, knowledge of swipeable functionality and of course Testing as well.

### PR DESCRIPTION
**Pull request by shreya-mishra**
Card UI fix on the Goals page as per the GET response of the API.

### CODE REVIEW

File: src/components/ToDoComponent/TodoComponent.tsx [hunk 1]
```diff
@@ -1,25 +1,26 @@
...
   useEffect(() => {
-    getTodos()
+    getTodos();
   }, [changed, tasks]);
 
-  const getTodos = async() => {
-    const todos = await fetch('https://backend-goals-production.up.railway.app/goal/');
+  const getTodos = async () => {
+    const todos = await fetch(
+      'https://backend-goals-production.up.railway.app/goal/',
```
Comment (sahsisunny) [inline src/components/ToDoComponent/TodoComponent.tsx]: Can you please create a constant for this URL?

Comment (shreya-mishra) [reply src/components/ToDoComponent/TodoComponent.tsx]: moved
