### PR TITLE
fixed the bugs of To do component's animated card

### LINKED ISSUE #140: Todo list swipe performance

### PR DESCRIPTION
**Pull request by vinayak-trivedi**
closes #140 
### What was the Issue 
- when the user was clicking on the checkbox multiple times it was crashing, 
- when the user was swiping the animated component continuously then also the app was crashing

fixed both the issues

**Anyone reviewing this PR, please run it on your phone to check if it is working fine**

### video for reference
 

https://user-images.githubusercontent.com/90315175/192683701-797eab74-dbf2-4208-be90-c9b90245df1a.mp4

### CODE REVIEW

**Review by dakshbhardwaj — DISMISSED** [review]

**Comment by dakshbhardwaj** [comment]
LGTM

File: src/components/ToDoComponent/TodoComponent.tsx [hunk 1]
```diff
@@ -3,42 +3,54 @@ import React, { useEffect, useState } from 'react';
...
-    tasks.shift();
-    tasks.push(newData[0]);
-    position !== tasks[tasks.length - 1].id
-      ? setpostion(tasks[position + 1].id)
-      : setpostion(tasks[0].id);
+  useEffect(() => {
+    setTasks(tasks);
+  }, [changed, tasks]);
+
+  const changeCardFunction = () => {
```
Comment (bajajcodes) [inline src/components/ToDoComponent/TodoComponent.tsx:17]: My believe there is no need of `useEffect` and `change` state:
```js
  const changeCardFunction = (id: number) => {
    if (tasks.length !== 1) {
      const task = tasks[0];
      const redorderdTasks = tasks.filter((t) => t.id !== id);
      setTasks([...redorderdTasks, task]);
    }
  };
  ```

File: src/components/ToDoComponent/TodoComponent.tsx [hunk 2]
```diff
@@ -3,42 +3,54 @@ import React, { useEffect, useState } from 'react';
 import Card from './Card';
 import data from './Data';
 import { TodoStyles } from './Styles/TodoStyles';
+import Task from './taskType';
 
 const TodoComponent = () => {
   const [tasks, setTasks] = useState(data);
```
Comment (bajajcodes) [inline src/components/ToDoComponent/TodoComponent.tsx]: const [tasks, setTasks] = useState<Task[]>(data);

File: src/components/ToDoComponent/TodoComponent.tsx (hunk 1 above)
Comment (pranikz) [reply src/components/ToDoComponent/TodoComponent.tsx:17]: +1

Comment (vinayak-trivedi) [reply src/components/ToDoComponent/TodoComponent.tsx:17]: hey @shmbajaj I've tried this solution, this creates some problems, so if a user swipes that component multiple times it leads to duplication of that component and we get an error `Encountered two children with the same key`

Comment (vinayak-trivedi) [reply src/components/ToDoComponent/TodoComponent.tsx:17]: so that is why I was using shift to remove that component and push it back to the end of array

File: src/components/ToDoComponent/TodoComponent.tsx (hunk 2 above)
Comment (vinayak-trivedi) [reply src/components/ToDoComponent/TodoComponent.tsx]: made this change in recent commit

File: src/components/ToDoComponent/TodoComponent.tsx (hunk 1 above)
Comment (bajajcodes) [reply src/components/ToDoComponent/TodoComponent.tsx:17]: Though is `tasks` should be read-only and `setTasks` is enought for rerendering.
```js
    const reorderedTasks = [...tasks];
    const t = reorderedTasks.shift() as Task;
    setTasks([...reorderedTasks, t]);
```

Comment (bajajcodes) [reply src/components/ToDoComponent/TodoComponent.tsx:17]: > hey @shmbajaj I've tried this solution, this creates some problems, so if a user swipes that component multiple times it leads to duplication of that component and we get an error `Encountered two children with the same key`

Can you guide to reproduce this error.

**Review by bajajcodes — DISMISSED** [review]

File: __tests__/Component-test.tsx [hunk 3]
```diff
@@ -1,18 +1,27 @@
-import React from "react";
-import {fireEvent, render} from "@testing-library/react-native"
-import ShortGoalsComponent from "../src/components/ShortGoalsComponent/ShortGoalsComponent";
+import React from 'react';
```
Comment (shreya-mishra) [inline __tests__/Component-test.tsx:1]: why this inverted comma's change?

File: __tests__/Component-test.tsx [hunk 4]
```diff
@@ -1,18 +1,27 @@
...
+import { fireEvent, render } from '@testing-library/react-native';
```
Comment (shreya-mishra) [inline __tests__/Component-test.tsx:2]: +1

File: __tests__/Component-test.tsx [hunk 5]
```diff
@@ -1,18 +1,27 @@
...
+import ShortGoalsComponent from '../src/components/ShortGoalsComponent/ShortGoalsComponent';
```
Comment (shreya-mishra) [inline __tests__/Component-test.tsx:3]: +1

File: babel.config.js [hunk 6]
```diff
@@ -1,6 +1,4 @@
 module.exports = {
   presets: ['module:metro-react-native-babel-preset'],
-  plugins: [
-    "react-native-reanimated/plugin",
-  ],
+  plugins: ['react-native-reanimated/plugin'],
```
Comment (shreya-mishra) [inline babel.config.js:3]: what's the change ?

**Review by shreya-mishra — CHANGES_REQUESTED** [review]
Do I really need to review those files which don't have any change , it just have a change of either pretittier or  LF /CRLF

File: babel.config.js (hunk 6 above)
Comment (vinayak-trivedi) [reply babel.config.js:3]: it's a change done by prettier, all the other changes are that as well

File: __tests__/Component-test.tsx (hunk 5 above)
Comment (vinayak-trivedi) [reply __tests__/Component-test.tsx:3]: it's done by prettier, marking this and the previous ones resolved

**Review by shreya-mishra — APPROVED** [review]
